# Docker Compose - Development Environment
services:
  client:
    image: client:development
    container_name: bibble-client
    build:
      context: ./client
      target: build
    command: npm run dev
    ports:
      - '3000:5173'
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: always
    networks:
      - bibble-network

  server:
    image: server:development
    container_name: bibble-server
    build:
      context: ./server
      target: development
    ports:
      - '8080:8080'
    command: npm start dev
    depends_on:
      - postgres
    # environment: INCLUDE ENVIRONMENT VARIABLES HERE
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - bibble-network

  nginx:
    image: nginx:latest
    container_name: bibble-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - client
      - server
    restart: always
    networks:
      - bibble-network

  postgres:
    image: postgres:latest
    container_name: bibble-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - bibble-network

networks:
  bibble-network:
    driver: bridge