version: '3'

services:
  bibble-client:
    image: bibble-client
    container_name: bibble-client
    build:
      context: ./bibble-client
    ports:
      - '3000:3000'
    volumes:
      - ./bibble-client:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - bibble-network

  bibble-kennel-api:
    image: bibble-kennel-api
    container_name: bibble-kennel-api
    build:
      context: ./bibble-kennel-api
    ports:
      - '8000:8000'
    logging:
      driver: json-file
    volumes:
      - ./bibble-kennel-api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - bibble-network
    depends_on:
      - bibble-kennel-mongo

  bibble-kennel-mongo:
    image: mongo:latest
    container_name: bibble-kennel-mongo
    command: --port 27017
    ports:
      - '27017:27017'
    volumes:
      - bibble-kennel-mongo-data:/data/db
    networks:
      - bibble-network

  bibble-user-api:
    image: bibble-user-api
    container_name: bibble-user-api
    build:
      context: ./bibble-user-api
    ports:
      - '8001:8001'
    logging:
      driver: json-file
    volumes:
      - ./bibble-user-api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - bibble-network
    depends_on:
      - bibble-user-mongo

  bibble-user-mongo:
    image: mongo:latest
    container_name: bibble-user-mongo
    command: --port 27018
    ports:
      - '27018:27018'
    volumes:
      - bibble-user-mongo-data:/data/db
    networks:
      - bibble-network

  bibble-nginx:
    image: nginx:latest
    container_name: bibble-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bibble-network
    depends_on:
      - bibble-client
      - bibble-kennel-api
      - bibble-user-api

networks:
  bibble-network:
    driver: bridge

volumes:
  bibble-kennel-mongo-data:
    driver: local
  bibble-user-mongo-data:
    driver: local
