version: '3'

services:
  client:
    container_name: bibble-client
    build:
      context: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app # Mount the client source code directory as a volume

  server:
    container_name: bibble-server
    build:
      context: ./server
    ports:
      - '8000:8000'
    logging:
      driver: json-file
    volumes:
      - ./server:/app # Mount the server source code directory as a volume

  nginx:
    image: nginx:latest
    container_name: bibble-nginx
    ports:
      - '80:80' # Expose Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Mount the Nginx configuration file
    depends_on:
      - client # Wait until Client app container is up
      - server # Wait until Server app container is up
