export const cats = [
  'Abyssinian',
  'Aegean',
  'American Curl',
  'American Bobtail',
  'American Shorthair',
  'American Wirehair',
  'Arabian Mau',
  'Australian Mist',
  'Asian',
  'Asian Semi-longhair',
  'Balinese',
  'Bambino',
  'Bengal',
  'Birman',
  'Bombay',
  'Brazilian Shorthair',
  'British Semi-longhair',
  'British Shorthair',
  'British Longhair',
  'Burmese',
  'Burmilla',
  'California Spangled',
  'Chantilly-Tiffany',
  'Chartreux',
  'Chausie',
  'Cheetoh',
  'Colorpoint Shorthair',
  'Cornish Rex',
  'Cymric',
  'Cyprus',
  'Devon Rex',
  'Donskoy',
  'Dragon Li',
  'Dwarf cat',
  'Egyptian Mau',
  'European Shorthair',
  'Exotic Shorthair',
  'Foldex',
  'German Rex',
  'Havana Brown',
  'Highlander',
  'Himalayan',
  'Japanese Bobtail',
  'Javanese',
  'Karelian Bobtail',
  'Khao Manee',
  'Korat',
  'Korean Bobtail',
  'Korn Ja',
  'Kurilian Bobtail',
  'LaPerm',
  'Lykoi',
  'Maine Coon',
  'Manx',
  'Mekong Bobtail',
  'Minskin',
  'Munchkin',
  'Nebelung',
  'Napoleon',
  'Norwegian Forest cat',
  'Ocicat',
  'Ojos Azules',
  'Oregon Rex',
  'Oriental Bicolor',
  'Oriental Shorthair',
  'Oriental Longhair',
  'PerFold',
  'Persian (Modern Persian Cat)',
  'Persian (Traditional Persian Cat)',
  'Peterbald',
  'Pixie-bob',
  'Raas',
  'Ragamuffin',
  'Ragdoll',
  'Russian Blue',
  'Russian White, Black and Tabby',
  'Sam Sawet',
  'Savannah',
  'Scottish Fold',
  'Selkirk Rex',
  'Serengeti',
  'Serrade petit',
  'Siamese',
  'Siberian',
  'Singapura',
  'Snowshoe',
  'Sokoke',
  'Somali',
  'Sphynx',
  'Suphalak',
  'Thai',
  'Thai Lilac',
  'Tonkinese',
  'Toyger',
  'Turkish Angora',
  'Turkish Van',
  'Ukrainian Levkoy'
];

export const catHairCoats = [
  'Short Smooth',
  'Long Silky',
  'Medium Plush',
  'Short Wirehaired',
  'Long Hair',
  'Curly',
  'Wavy',
  'Sphynx (Hairless)',
  'Double Coated',
  'Single Coated',
  'Dense',
  'Sparse',
  'Velvet',
  'Satin',
  'Tabby',
  'Calico',
  'Tortoiseshell',
  'Pointed',
  'Tuxedo',
  'Bicolor'
];

export const catVaccines = [
  { name: 'Feline Panleukopenia (Feline Distemper) Vaccine', isCore: true },
  { name: 'Feline Calicivirus Vaccine', isCore: true },
  { name: 'Feline Herpesvirus (Rhinotracheitis) Vaccine', isCore: true },
  { name: 'Rabies Vaccine', isCore: false },
  { name: 'Feline Leukemia (FeLV) Vaccine', isCore: false },
  { name: 'Feline Immunodeficiency Virus (FIV) Vaccine', isCore: false },
  { name: 'Feline Infectious Peritonitis (FIP) Vaccine', isCore: false },
  { name: 'Chlamydophila Felis Vaccine', isCore: false },
  { name: 'Bordetella Bronchiseptica Vaccine', isCore: false },
  { name: 'Giardia Vaccine', isCore: false }
];

export const catLegalTags = [
  'Microchipped',
  'Neutered/Spayed',
  'Vaccinated',
  'Licensed',
  'HDB Approved Breed',
  'Commercially Imported (with proper documentation)',
  'Passed Basic Obedience Training (for specific breeds)',
  'Insured (for liability in some cases)',
  'Registered with a Breed Club (for pedigree dogs)',
  'Has Pet Passport (for international travel)'
];
